Versions:
  type: object
  properties:
    v: 
      type: string
    cv:
      type: string
Meta:
  type: object
  properties:
    mod:
      type: integer
    scm:
      type: integer
    usn:
      type: integer
    ts:
      type: integer
    musn:
      type: integer
    uname:
      type: string
    msg:
      type: string
    cont:
      type: boolean
    hostNum:
      type: integer